[package]
name = "yaag_proc_macro"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.102"
syn = { version = "2.0.108", features = ["printing", "full"] }
quote = "1.0.41"
