[package]
name = "do_you_yield"
version = "0.1.0"
edition.workspace = true

[dev-dependencies]
trybuild = "1.0"

[dependencies]
do_you_yield_macro.workspace = true
futures-core = { version = "0.3.31", optional = true }

[features]
default = [ "async" ]
async = [ "futures-core" ]
